(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=t(r);fetch(r.href,s)}})();async function h(e){if(!e)return null;const n=await fetch(`https://openlibrary.org/search.json?q=${encodeURIComponent(e)}`);if(!n.ok)throw new Error("Network error");return(await n.json()).docs}const m="/book-catalogue/assets/No_Cover.jpg",y="favorite_books";function l(){const e=localStorage.getItem("favorite_books");return e?JSON.parse(e):[]}function v(e){let n=l(),t;const o=n.findIndex(r=>r.key===e.key);if(o===-1){const r={key:e.key,title:e.title,author_name:e.author_name,cover_i:e.cover_i,first_publish_year:e.first_publish_year};n.push(r),t=!0}else n.splice(o,1),t=!1;return localStorage.setItem(y,JSON.stringify(n)),t}function u(){const e=l(),n=document.getElementById("favoritesList");if(n.innerHTML="",e.length===0){n.innerHTML='<p class="empty-msg">No books saved.</p>';return}e.forEach(t=>{var s;const o=document.createElement("div");o.className="fav-card";const r=t.cover_i?`https://covers.openlibrary.org/b/id/${t.cover_i}-S.jpg`:m;o.innerHTML=`
            <img src="${r}" alt="${t.title}" class="fav-cover">
            <div class="fav-details">
                <span class="fav-title">${t.title}</span>
                <span class="fav-author">${((s=t.author_name)==null?void 0:s[0])||"Unknown"}</span>
                <span class="fav-year">${t.first_publish_year||""}</span>
            </div>
            <button class="remove-fav-btn" data-id="${t.key}">🤍</button>
        `,n.appendChild(o)})}function b(e,n=500){let t;return function(...o){t&&clearTimeout(t),t=setTimeout(()=>{e.apply(this,o)},n)}}const d=document.getElementById("themeToggle"),L=document.getElementById("searchInput"),c=document.getElementById("results"),i=document.getElementById("status"),T=document.getElementById("favoritesList");let p=[];function _(e){c.innerHTML="";const n=l();if(e.length===0){i.innerText="Sorry, we couldnt find any books";return}e.forEach(t=>{var f;const o=n.some(g=>g.key===t.key),r=t.cover_i,s=r?`https://covers.openlibrary.org/b/id/${r}-M.jpg`:m,a=document.createElement("div");a.className="book-card",a.innerHTML=`
            <img src="${s}" alt="${t.title}">
            <div class="book-info">
                <h4 class='book-title'>${t.title}</h4>
                <p class='book-author'>${((f=t.author_name)==null?void 0:f[0])||"Unknown"}</p>
                <p class='book-year'>${t.first_publish_year}
            </div>
            <button class="fav-btn" data-id="${t.key}">${o?"❤️":"🤍"}</button>
        `,c.appendChild(a)})}async function E(e){if(e.length<3){c.innerHTML="",i.innerText="Insert minimum 3 characters...";return}i.innerText="Loading...";try{const n=await h(e);i.innerText=`Found: ${n.length}`,p=n,_(n)}catch(n){i.innerText="Error: "+n.message}}const k=b(e=>E(e),500);L.addEventListener("input",e=>{k(e.target.value)});c.addEventListener("click",e=>{if(e.target.classList.contains("fav-btn")){const n=e.target.dataset.id,t=p.find(o=>o.key==n);if(t){const o=v(t);e.target.innerText=o?"❤️":"🤍",u()}}});d.addEventListener("click",()=>{document.body.classList.toggle("dark-theme");const e=document.body.classList.contains("dark-theme");localStorage.setItem("theme",e?"dark":"light"),d.innerText=e?"☀️":"🌙"});T.addEventListener("click",e=>{const n=e.target.closest(".remove-fav-btn");if(!n)return;const t=n.dataset.id,r=l().find(s=>s.key===t);if(r){v(r),u();const s=document.querySelector(`.fav-btn[data-id="${t}"]`);s&&(s.innerText="🤍")}});localStorage.getItem("theme")==="dark"&&(document.body.classList.add("dark-theme"),d.innerText="☀️");u();
